//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Web;
namespace Lab02CRUD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Employee
    {
        public int EmployeeId { get; set; }

        [Required(ErrorMessage ="Họ tên không được để trống.")]
        [StringLength(50,MinimumLength = 6,ErrorMessage ="Tên của bạn phải dài từ [6-50] chữ cái.")]
        public string Name { get; set; }

        [Required(ErrorMessage ="Chức vụ không được để trống.")]
        [StringLength(50,MinimumLength =8,ErrorMessage ="Chức vụ phải dài từ [8-50] chữ cái.")]
        public string Position { get; set; }

        [Required(ErrorMessage ="Văn phòng không được để trống.")]
        [StringLength(50,MinimumLength =5,ErrorMessage ="Văn phòng phải dài từ [5-50] chữ cái.")]
        public string Office { get; set; }

        [Required(ErrorMessage ="Tiền lương không được để trống.")]
        public Nullable<int> Salary { get; set; }

        [DisplayName("Avartar")]
        public string ImagePath { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }

        public Employee() {
            ImagePath = "~/AppFiles/Images/default.png";
        }
    }
}
